# 오늘 계획

- [x] DrawingApp 피드백 사항 진행 및 README 작성
- [x] 알고리즘 스터디 문제풀기
- [x] 동시성 프로그래밍 인강 보기
- [x] Swift 기술면접 스터디 준비

# 회고

> 자유롭게 진행하려고 생각해서 그런지, 월요일이라서 그런건지 집중이 잘 됐다. 내일도 계획했던 부분 열심히 해보고, 어려운 내용을 마주해서 풀어봐야겠다.

# ARC/클로저의 캡처 리스트

- 새로 배웠던 내용

	- 클로저의 경우, 캡처 리스트 내에서 `weak/ unowned` 문구를 사용해 클로저가 가리키려는 인스턴스의 참조 카운팅을 올리지 않음으로써 강한 참조 사이클을 막을 수 있다.

		- 강한 참조 예제

			```swift
			class ViewController: UIViewController {
			    var name: String = "뷰컨"
			    
			    func doSomething() {
			        DispatchQueue.global().async {
			            sleep(3)
			            print("글로벌 큐에서 출력: \(self.name)")
			            
			            DispatchQueue.main.async {
			                print("메인 큐에서 출력: \(self.name)")
			            }
			        }
			    }
			    
			    deinit {
			        print("\(name) 메모리 해제")
			    }
			}
			
			func localScopeFunction() {
			    let vc = ViewController()
			    vc.doSomething()
			}
			
			localScopeFunction()
			```

			<img src="https://user-images.githubusercontent.com/92504186/160441171-5c50cce4-1647-44c0-b57d-264a4bea2092.jpg" alt="SS 2022-03-29 AM 01 10 24" width="40%;" />

			- 글로벌 큐의 클로저가 self를 강하게 참조하기 때문에 VC의 참조 카운팅이 올라간채로 유지되어, VC가 스택 메모리 상에서 해제되었음에도 3초 뒤에 클로저 내의 문구들을 출력한 뒤 해제된다.(강한 순환 참조가 일어나진 않지만, VC가 사라졌음에도 머물러있게 된다.)

		- 약한 참조 예제

			```swift
			class ViewController: UIViewController {
			    var name: String = "뷰컨"
			    
			    func doSomething() {
			        DispatchQueue.global().async { [weak self] in
			            sleep(3)
			            print("글로벌 큐에서 출력: \(self?.name)")
			            DispatchQueue.main.async {
			                print("메인 큐에서 출력: \(self?.name)")
			            }
			        }
			    }
			    deinit {
			        print("\(name) 메모리 해제")
			    }
			}
			
			func localScopeFunction() {
			    let vc = ViewController()
			    vc.doSomething()
			}
			
			localScopeFunction()
			```

			<img src="https://user-images.githubusercontent.com/92504186/160441584-06389af5-0380-4e62-b63f-8a4970ff797e.jpg" alt="SS 2022-03-29 AM 01 12 42" width="40%;" />

			- 이 경우에는 클로저 내에서 self에 대한 참조가 약한 참조이기 때문에, VC가 해제됨과 동시에 클로저 내에서 참조할 수 없게 되고, VC는 참조 카운팅이 0이기 때문에 클로저 실행 전에 메모리에서 해제된다.